---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: zcash-android-sdk-lint
spec:
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: lint
      image: electriccoinco/zcash-android-builder:latest
      script: |
        cd source
        env | sort
        pwd
        ls -la
        ./gradlew ciLint --stacktrace --console=plain \
          -Duser.home=/tekton/home \
          -Dgradle.user.home=/tekton/home/.gradle
      securityContext:
        runAsUser: 0
